/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package translate;

//import translate.Sintax;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.io.StringReader;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;

/**
 *
 * @author vh367
 */
public class Principal extends javax.swing.JFrame {
 
    
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        
    }
    
    public class diccionario{
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTraducir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtextPalabra = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtextPalabra1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTraducir.setText("Traducir");
        btnTraducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraducirActionPerformed(evt);
            }
        });

        jtextPalabra.setColumns(20);
        jtextPalabra.setRows(5);
        jScrollPane1.setViewportView(jtextPalabra);

        jLabel1.setText("Español");

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Dubai", 1, 48)); // NOI18N
        jLabel5.setText("<>");

        jLabel2.setText("Ingles");

        jtextPalabra1.setColumns(20);
        jtextPalabra1.setRows(5);
        jScrollPane2.setViewportView(jtextPalabra1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(115, 115, 115)
                .addComponent(jButton1)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(btnTraducir))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(btnTraducir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTraducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraducirActionPerformed
        // TODO add your handling code here:
        HashMap diccionario = new HashMap();
diccionario.put("cama", "bed");
diccionario.put("factura", "invoice");
diccionario.put("pájaro", "bird");
diccionario.put("sangre", "blood");
diccionario.put("bote", "boat");
diccionario.put("cuerpo", "body");
diccionario.put("hueso", "bone");
diccionario.put("libro", "book");
diccionario.put("fondo", "bottom");
diccionario.put("caja", "box");
diccionario.put("niño", "child");
diccionario.put("hermano", "brother");
diccionario.put("edificio", "building");
diccionario.put("negocio", "business");
diccionario.put("llamada", "call");
diccionario.put("capital", "capital");
diccionario.put("caso", "case");
diccionario.put("gato", "cat");
diccionario.put("causa", "cause");
diccionario.put("centavo", "cent");
diccionario.put("centro", "center");
diccionario.put("siglo", "century");
diccionario.put("oportunidad", "opportunity");
diccionario.put("cambio", "change");
diccionario.put("verificación", "verification");
diccionario.put("iglesia", "church");
diccionario.put("círculo", "circle");
diccionario.put("ciudad", "city");
diccionario.put("clase", "class");
diccionario.put("ropa", "clothing");
diccionario.put("nube", "cloud");
diccionario.put("costa", "coast");
diccionario.put("color", "color");
diccionario.put("compañía", "company");
diccionario.put("consonante", "consonant");
diccionario.put("copia", "copy");
diccionario.put("maíz", "corn");
diccionario.put("algodón", "cotton");
diccionario.put("país", "country");
diccionario.put("curso", "course");
diccionario.put("vaca", "cow");
diccionario.put("multitud", "crowd");
diccionario.put("día", "day");
diccionario.put("diccionario", "dictionary");
diccionario.put("dirección", "address");
diccionario.put("distancia", "distance");
diccionario.put("doctor", "doctor");
diccionario.put("dólar", "dollar");
diccionario.put("puerta", "door");
diccionario.put("oreja", "ear");
diccionario.put("tierra", "earth");
diccionario.put("huevo", "egg");
diccionario.put("energía", "energy");
diccionario.put("ejemplo", "example");
diccionario.put("experiencia", "experience");
diccionario.put("ojo", "eye");
diccionario.put("juego", "game");
diccionario.put("jardín", "garden");
diccionario.put("gas", "gas");
diccionario.put("niña", "girl");
diccionario.put("vidrio", "glass");
diccionario.put("oro", "gold");
diccionario.put("gobierno", "government");
diccionario.put("césped", "grass");
diccionario.put("grupo", "group");
diccionario.put("cabello", "hair");
diccionario.put("martillo", "hammer");
diccionario.put("mano", "hand");
diccionario.put("sombrero", "hat");
diccionario.put("cabeza", "head");
diccionario.put("corazón", "heart");
diccionario.put("historia", "history");
diccionario.put("hueco", "hole");
diccionario.put("hogar", "home");
diccionario.put("esperanza", "hope");
diccionario.put("caballo", "horse");
diccionario.put("hospital", "hospital");
diccionario.put("hotel", "hotel");
diccionario.put("hora", "hour");
diccionario.put("helado", "ice cream");
diccionario.put("idea", "idea");
diccionario.put("imperio", "empire");
diccionario.put("información", "information");
diccionario.put("insecto", "insect");
diccionario.put("interés", "interest");
diccionario.put("isla", "island");
diccionario.put("trabajo", "job");
diccionario.put("joya", "jewel");
diccionario.put("niño", "kid");
diccionario.put("beso", "kiss");
diccionario.put("cuchillo", "knife");
diccionario.put("laboratorio", "laboratory");
diccionario.put("lago", "lake");
diccionario.put("lenguaje", "language");
diccionario.put("risa", "laughter");
diccionario.put("ley", "law");
diccionario.put("hoja", "leaf");
diccionario.put("pierna", "leg");
diccionario.put("león", "lion");
diccionario.put("lista", "list");
diccionario.put("luz", "light");
diccionario.put("línea", "line");
diccionario.put("labio", "lip");
diccionario.put("amor", "love");
diccionario.put("mapa", "map");
diccionario.put("mar", "sea");
diccionario.put("máscara", "mask");
diccionario.put("comida", "food");
diccionario.put("mes", "month");
diccionario.put("madre", "mother");
diccionario.put("montaña", "mountain");
diccionario.put("ratón", "mouse");
diccionario.put("boca", "mouth");
diccionario.put("músculo", "muscle");
diccionario.put("música", "music");
diccionario.put("nariz", "nose");
diccionario.put("nota", "note");
diccionario.put("número", "number");
diccionario.put("objeto", "object");
diccionario.put("océano", "ocean");
diccionario.put("oficina", "office");
diccionario.put("aceite", "oil");
diccionario.put("naranja", "orange");
diccionario.put("orden", "order");
diccionario.put("pintura", "painting");
diccionario.put("papel", "paper");
diccionario.put("parque", "park");
diccionario.put("partido", "match");
diccionario.put("paz", "peace");
diccionario.put("pluma", "pen");
diccionario.put("persona", "person");
diccionario.put("fotografía", "photograph");
diccionario.put("piano", "piano");
diccionario.put("imagen", "picture");
diccionario.put("planta", "plant");
diccionario.put("bolsillo", "pocket");
diccionario.put("policía", "police");
diccionario.put("política", "politics");
diccionario.put("pollito", "chick");
diccionario.put("piscina", "pool");
diccionario.put("puerto", "port");
diccionario.put("problema", "problem");
diccionario.put("producto", "product");
diccionario.put("proyecto", "project");
diccionario.put("pregunta", "question");
diccionario.put("conejo", "rabbit");
diccionario.put("lluvia", "rain");
diccionario.put("arco iris", "rainbow");
diccionario.put("rata", "rat");
diccionario.put("restaurante", "restaurant");
diccionario.put("anillo", "ring");
diccionario.put("río", "river");
diccionario.put("camino", "road");
diccionario.put("roca", "rock");
diccionario.put("habitación", "room");
diccionario.put("rosa", "rose");
diccionario.put("goma de borrar", "eraser");
diccionario.put("regla", "ruler");
diccionario.put("tristeza", "sadness");
diccionario.put("arena", "sand");
diccionario.put("escuela", "school");
diccionario.put("mar", "sea");
diccionario.put("asiento", "seat");
diccionario.put("semáforo", "traffic light");
diccionario.put("serpiente", "snake");
diccionario.put("nieve", "snow");
diccionario.put("sociedad", "society");
diccionario.put("hijo", "son");
diccionario.put("sonrisa", "smile");
diccionario.put("nieve", "snow");
diccionario.put("sol", "sun");
diccionario.put("mesa", "table");
diccionario.put("colita", "tail");
diccionario.put("tarea", "task");
diccionario.put("tecnología", "technology");
diccionario.put("teléfono", "telephone");
diccionario.put("televisión", "television");
diccionario.put("temporada", "season");
diccionario.put("tenis", "tennis");
diccionario.put("prueba", "test");
diccionario.put("tiempo", "time");
diccionario.put("herramienta", "tool");
diccionario.put("diente", "tooth");
diccionario.put("toque", "touch");
diccionario.put("ciudad", "town");
diccionario.put("juguetes", "toys");
diccionario.put("árbol", "tree");
diccionario.put("verdad", "truth");
diccionario.put("tortuga", "turtle");
diccionario.put("paraguas", "umbrella");
diccionario.put("universidad", "university");
diccionario.put("vacaciones", "vacation");
diccionario.put("vuelo", "flight");
diccionario.put("voz", "voice");
diccionario.put("muro", "wall");
diccionario.put("agua", "water");
diccionario.put("clima", "weather");
diccionario.put("ruido", "noise");
diccionario.put("boda", "wedding");
diccionario.put("semana", "week");
diccionario.put("bienvenida", "welcome");
diccionario.put("viento", "wind");
diccionario.put("invierno", "winter");
diccionario.put("mujer", "woman");
diccionario.put("trabajo", "work");
diccionario.put("mundo", "world");
diccionario.put("año", "year");
diccionario.put("joven", "young");
diccionario.put("menos", "less");
diccionario.put("poco", "little");
diccionario.put("mucho", "much");
diccionario.put("más", "more");
diccionario.put("muchos", "many");
diccionario.put("otro", "other");
diccionario.put("otros", "others");
diccionario.put("varios", "several");
diccionario.put("algunos", "some");
diccionario.put("tal", "such");
diccionario.put("el", "the");
diccionario.put("la", "the");
diccionario.put("los", "the");
diccionario.put("las", "the");
diccionario.put("un", "a");
diccionario.put("una", "a");
diccionario.put("Yo", "I");
diccionario.put("él", "he");
diccionario.put("ella", "she");
diccionario.put("ello", "it");
diccionario.put("nosotros", "we");
diccionario.put("ustedes", "you");
diccionario.put("ellos", "they");
diccionario.put("a", "to");
diccionario.put("de", "of");
diccionario.put("quién", "who");
diccionario.put("qué", "what");
diccionario.put("cuál", "which");
diccionario.put("es", "is");
diccionario.put("son", "are");
diccionario.put("soy", "I am");
diccionario.put("abandonar", "abandon");
diccionario.put("abolir", "abolish");
diccionario.put("absolver", "absolve");
diccionario.put("absorber", "absorb");
diccionario.put("abusar", "abuse");
diccionario.put("acceder", "access");
diccionario.put("acelerar", "accelerate");
diccionario.put("acentuar", "accentuate");
diccionario.put("aceptar", "accept");
diccionario.put("acusar", "accuse");
diccionario.put("acostumbrar", "accustom");
diccionario.put("lograr", "achieve");
diccionario.put("adquirir", "acquire");
diccionario.put("actuar", "act");
diccionario.put("añadir", "add");
diccionario.put("dirigirse", "address");
diccionario.put("admirar", "admire");
diccionario.put("admitir", "admit");
diccionario.put("adorar", "adore");
diccionario.put("adornar", "adorn");
diccionario.put("avanzar", "advance");
diccionario.put("anunciar", "announce");
diccionario.put("aconsejar", "advise");
diccionario.put("afirmar", "affirm");
diccionario.put("estar", "be");
diccionario.put("acuerdo", "agreement");
diccionario.put("permitir", "allow");
diccionario.put("ascender", "ascend");
diccionario.put("divertir", "amuse");
diccionario.put("molestar", "annoy");
diccionario.put("responder", "answer");
diccionario.put("disculparse", "apologize");
diccionario.put("aparecer", "appear");
diccionario.put("nombrar", "appoint");
diccionario.put("acercarse", "approach");
diccionario.put("aprobar", "approve");
diccionario.put("organizar", "arrange");
diccionario.put("llegar", "arrive");
diccionario.put("preguntar", "ask");
diccionario.put("asegurar", "assure");
diccionario.put("sorprender", "surprise");
diccionario.put("atacar", "attack");
diccionario.put("intentar", "attempt");
diccionario.put("asistir", "attend");
diccionario.put("atraer", "attract");
diccionario.put("evitar", "avoid");
diccionario.put("bañar", "bathe");
diccionario.put("rogar", "beg");
diccionario.put("creer", "believe");
diccionario.put("pertenecer", "belong");
diccionario.put("culpar", "blame");
diccionario.put("reservar", "book");
diccionario.put("llamar", "call");
diccionario.put("llevar", "carry");
diccionario.put("cobrar", "charge");
diccionario.put("cesar", "cease");
diccionario.put("cambiar", "change");
diccionario.put("verificar", "check");
diccionario.put("limpiar", "clean");
diccionario.put("despejar", "clear");
diccionario.put("trepar", "climb");
diccionario.put("cerrar", "close");
diccionario.put("recoger", "collect");
diccionario.put("peinar", "comb");
diccionario.put("combinar", "combine");
diccionario.put("ordenar", "order");
diccionario.put("comprometer", "commit");
diccionario.put("comparar", "compare");
diccionario.put("quejarse", "complain");
diccionario.put("componer", "compose");
diccionario.put("ocultar", "hide");
diccionario.put("considerar", "consider");
diccionario.put("consistir", "consist");
diccionario.put("contener", "contain");
diccionario.put("continuar", "continue");
diccionario.put("copiar", "copy");
diccionario.put("corregir", "correct");
diccionario.put("toser", "cough");
diccionario.put("contar", "count");
diccionario.put("cubrir", "cover");
diccionario.put("cruzar", "cross");
diccionario.put("coronar", "crown");
diccionario.put("llorar", "cry");
diccionario.put("dañar", "damage");
diccionario.put("bailar", "dance");
diccionario.put("amanecer", "dawn");
diccionario.put("engañar", "deceive");
diccionario.put("decidir", "decide");
diccionario.put("declarar", "declare");
diccionario.put("defender", "defend");
diccionario.put("entregar", "deliver");
diccionario.put("desear", "desire");
diccionario.put("despreciar", "despise");
diccionario.put("destruir", "destroy");
diccionario.put("separar", "separate");
diccionario.put("desarrollar", "develop");
diccionario.put("dedicar", "dedicate");
diccionario.put("devorar", "devour");
diccionario.put("descubrir", "discover");
diccionario.put("gustar", "like");
diccionario.put("dividir", "divide");
diccionario.put("arrastrar", "drag");
diccionario.put("dejar", "leave");
diccionario.put("caer", "fall");
diccionario.put("secar", "dry");
diccionario.put("ganar", "win");
diccionario.put("elegir", "choose");
diccionario.put("emplear", "employ");
diccionario.put("incluir", "include");
diccionario.put("alentar", "encourage");
diccionario.put("terminar", "finish");
diccionario.put("disfrutar", "enjoy");
diccionario.put("entrar", "enter");
diccionario.put("establecer", "establish");
diccionario.put("estimar", "estimate");
diccionario.put("evocar", "evoke");
diccionario.put("intercambiar", "exchange");
diccionario.put("esperar", "wait");
diccionario.put("explicar", "explain");
diccionario.put("explotar", "exploit");
diccionario.put("exponer", "expose");
diccionario.put("expresar", "express");
diccionario.put("extraer", "extract");
diccionario.put("fallar", "fail");
diccionario.put("temer", "fear");
diccionario.put("buscar", "search");
diccionario.put("llenar", "fill");
diccionario.put("pescar", "fish");
diccionario.put("quedar", "stay");
diccionario.put("arreglar", "fix");
diccionario.put("flotar", "float");
diccionario.put("doblar", "fold");
diccionario.put("seguir", "follow");
diccionario.put("fundar", "found");
diccionario.put("jugar", "play");
diccionario.put("reunir", "gather");
diccionario.put("gobernar", "govern");
diccionario.put("otorgar", "grant");
diccionario.put("saludar", "greet");
diccionario.put("proteger", "protect");
diccionario.put("adivinar", "guess");
diccionario.put("manejar", "handle");
diccionario.put("colgar", "hang");
diccionario.put("ocurrir", "occur");
diccionario.put("odiar", "hate");
diccionario.put("calentar", "heat");
diccionario.put("ayudar", "help");
diccionario.put("contratar", "hire");
diccionario.put("cazar", "hunt");
diccionario.put("apresurarse", "hurry");
diccionario.put("imaginar", "imagine");
diccionario.put("insinuar", "insinuate");
diccionario.put("importar", "matter");
diccionario.put("impressionar", "impress");
diccionario.put("mejorar", "improve");
diccionario.put("aumentar", "increase");
diccionario.put("inventar", "invent");
diccionario.put("invitar", "invite");
diccionario.put("planchar", "iron");
diccionario.put("unirse", "join");
diccionario.put("bromear", "joke");
diccionario.put("saltar", "jump");
diccionario.put("justificar", "justify");
diccionario.put("golpear", "hit");
diccionario.put("mantener", "keep");
diccionario.put("saber", "know");
diccionario.put("reír", "laugh");
diccionario.put("último", "last");
diccionario.put("mentir", "lie");
diccionario.put("prestar", "lend");
diccionario.put("perder", "lose");
diccionario.put("ampliar", "widen");
diccionario.put("hacer", "make");
diccionario.put("gestionar", "manage");
diccionario.put("marcar", "mark");
diccionario.put("casarse", "marry");
diccionario.put("medir", "measure");
diccionario.put("encontrar", "find");
diccionario.put("reunirse", "meet");
diccionario.put("mencionar", "mention");
diccionario.put("mezclar", "mix");
diccionario.put("mover", "move");
diccionario.put("necesitar", "need");
diccionario.put("notar", "notice");
diccionario.put("observar", "observe");
diccionario.put("obtener", "obtain");
diccionario.put("ocurrir", "occur");
diccionario.put("abrirla", "open");
diccionario.put("operar", "operate");
diccionario.put("oponerse", "oppose");
diccionario.put("pedir", "ask");
diccionario.put("pagar", "pay");
diccionario.put("jugar", "play");
diccionario.put("expulsar", "expel");
diccionario.put("poder", "can");
diccionario.put("dar", "give");
diccionario.put("placer", "please");
diccionario.put("poner", "put");
diccionario.put("leer", "read");
diccionario.put("recibir", "receive");
diccionario.put("reconocer", "recognize");
diccionario.put("recomendar", "recommend");
diccionario.put("reflejar", "reflect");
diccionario.put("rehusar", "refuse");
diccionario.put("regalar", "give");
diccionario.put("regresar", "return");
diccionario.put("recordar", "remember");
diccionario.put("quitar", "remove");
diccionario.put("reparar", "repair");
diccionario.put("repetir", "repeat");
diccionario.put("reemplazar", "replace");
diccionario.put("responder", "respond");
diccionario.put("descansar", "rest");
diccionario.put("arriesgar", "risk");
diccionario.put("correr", "run");
diccionario.put("decir", "say");
diccionario.put("ver", "see");
diccionario.put("vender", "sell");
diccionario.put("enviar", "send");
diccionario.put("colocar", "place");
diccionario.put("servir", "serve");
diccionario.put("ajustar", "adjust");
diccionario.put("conjugar", "conjugate");
diccionario.put("separar", "separate");
diccionario.put("ser", "be");
diccionario.put("compartir", "share");
diccionario.put("disparar", "shoot");
diccionario.put("mostrar", "show");
diccionario.put("cerrar", "close");
diccionario.put("cantar", "sing");
diccionario.put("sentar", "sit");
diccionario.put("dormir", "sleep");
diccionario.put("deslizar", "slide");
diccionario.put("oler", "smell");
diccionario.put("hablar", "speak");
diccionario.put("gastar", "spend");
diccionario.put("empezar", "start");
diccionario.put("pararse", "stand");
diccionario.put("robar", "steal");
diccionario.put("detener", "stop");
diccionario.put("estudiar", "study");
diccionario.put("gritar", "yell");
diccionario.put("nadar", "swim");
diccionario.put("tomar", "take");
diccionario.put("enseñar", "teach");
diccionario.put("decir", "tell");
diccionario.put("pensar", "think");
diccionario.put("lanzar", "throw");
diccionario.put("entender", "understand");
diccionario.put("utilizar", "use");
diccionario.put("visitar", "visit");
diccionario.put("esperar", "wait");
diccionario.put("caminar", "walk");
diccionario.put("querer", "want");
diccionario.put("lavarse", "wash");
diccionario.put("trabajar", "work");
diccionario.put("escribir", "write");
diccionario.put("soltar", "drop");
diccionario.put("tocar", "touch");
diccionario.put("convertirse", "become");
diccionario.put("obtener", "get");
diccionario.put("necesitar", "need");
diccionario.put("hacer", "do");
diccionario.put("poder", "can");
diccionario.put("saber", "know");
diccionario.put("venir", "come");
diccionario.put("ver", "see");
diccionario.put("intentar", "try");
diccionario.put("decir", "say");
diccionario.put("pedir", "ask");
diccionario.put("dar", "give");
diccionario.put("ir", "go");
diccionario.put("volver", "return");
diccionario.put("pensar", "think");
diccionario.put("conseguir", "get");
diccionario.put("sentir", "feel");
diccionario.put("encontrar", "find");
diccionario.put("llamar", "call");
diccionario.put("venir", "come");
diccionario.put("hacer", "do");
diccionario.put("estar", "be");
diccionario.put("tener", "have");
diccionario.put("decir", "say");
diccionario.put("poder", "can");
diccionario.put("ir", "go");
diccionario.put("ver", "see");
diccionario.put("querer", "want");
diccionario.put("saber", "know");
diccionario.put("poner", "put");
diccionario.put("hablar", "speak");
diccionario.put("tomar", "take");
diccionario.put("llegar", "arrive");
diccionario.put("pensar", "think");
diccionario.put("encontrar", "find");
diccionario.put("escuchar", "listen");
diccionario.put("sentir", "feel");
diccionario.put("seguir", "follow");
diccionario.put("trabajar", "work");
diccionario.put("aprender", "learn");
diccionario.put("comenzar", "start");
diccionario.put("vivir", "live");
diccionario.put("llevar", "carry");
diccionario.put("mirar", "look");
diccionario.put("esperar", "wait");
diccionario.put("cambiar", "change");
diccionario.put("estudiar", "study");
diccionario.put("morir", "die");
diccionario.put("dejar", "leave");
diccionario.put("comer", "eat");
diccionario.put("deber", "must");
diccionario.put("sentar", "sit");
diccionario.put("dormir", "sleep");
diccionario.put("desear", "wish");
diccionario.put("gustar", "like");
diccionario.put("dividir", "divide");
diccionario.put("arrastrar", "drag");
diccionario.put("dejar", "leave");
diccionario.put("caer", "fall");
diccionario.put("secar", "dry");
diccionario.put("ganar", "win");
diccionario.put("elegir", "choose");
diccionario.put("emplear", "employ");
diccionario.put("incluir", "include");
diccionario.put("alentar", "encourage");
diccionario.put("terminar", "finish");
diccionario.put("disfrutar", "enjoy");
diccionario.put("entrar", "enter");
diccionario.put("establecer", "establish");
diccionario.put("estimar", "estimate");
diccionario.put("evocar", "evoke");
diccionario.put("intercambiar", "exchange");
diccionario.put("esperar", "wait");
diccionario.put("explicar", "explain");
diccionario.put("explotar", "exploit");
diccionario.put("exponer", "expose");
diccionario.put("expresar", "express");
diccionario.put("extraer", "extract");
diccionario.put("fallar", "fail");
diccionario.put("temer", "fear");
diccionario.put("buscar", "search");
diccionario.put("llenar", "fill");
diccionario.put("pescar", "fish");
diccionario.put("quedar", "stay");
diccionario.put("arreglar", "fix");
diccionario.put("flotar", "float");
diccionario.put("doblar", "fold");
diccionario.put("seguir", "follow");
diccionario.put("fundar", "found");
diccionario.put("jugar", "play");
diccionario.put("reunir", "gather");
diccionario.put("gobernar", "govern");
diccionario.put("otorgar", "grant");
diccionario.put("saludar", "greet");
diccionario.put("proteger", "protect");
diccionario.put("adivinar", "guess");
diccionario.put("manejar", "handle");
diccionario.put("colgar", "hang");
diccionario.put("ocurrir", "occur");
diccionario.put("odiar", "hate");
diccionario.put("calentar", "heat");
diccionario.put("ayudar", "help");
diccionario.put("contratar", "hire");
diccionario.put("cazar", "hunt");
diccionario.put("apresurarse", "hurry");

         
     
            String palabra = new String();
        String traducir = new String();
            palabra = jtextPalabra.getText();
            
           
        traducir = diccionario.get(palabra).toString();
          lblTraduccion.setText(traducir);
            
          
          
          File archivo = new File("archivo.txt");
        PrintWriter escribir;
        try {
            escribir = new PrintWriter(archivo);
            
            escribir.print(jtextPalabra.getText());
            
            escribir.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            Reader lector = new BufferedReader(new FileReader("archivo.txt"));
            Lexer lexer = new Lexer(lector);
            String resultado = "";
            while (true) {
                Tokens tokens = lexer.yylex();
                if (tokens == null) {
                    resultado += " FIN";
                    lblelex.setText(resultado);
                    return;
                    
                }
                switch(tokens){
                    case ERROR -> resultado += "Simbolo no definido\n";
                    
                    
                    
    case Inexistentes, factura, pájaro, sangre, bote, cuerpo, hueso, libro, 
            fondo, caja, niño, hermano, edificio, negocio, llamada, capital, caso, 
            gato, causa, centavo, centro, siglo, oportunidad, cambio, verificación,
            iglesia, círculo, ciudad, clase, ropa, nube, costa, color, compañía,
            consonante, copia, maíz, algodón, país, curso, vaca, multitud, día, 
            diccionario, dirección, distancia, doctor, dólar, puerta, oreja, tierra,
            huevo, energía, ejemplo, experiencia, ojo, juego, jardín, gas, niña,
            vidrio, oro, gobierno, césped, grupo, cabello, mano, sombrero, cabeza,
            corazón, calor, historia, agujero, hogar, caballo, hora, casa, hielo, 
            idea, pulgada, banco, industria, información, insecto, interés, hierro, 
            isla, trabajo, clave, lago, lenguaje, ley, pierna, nivel, mentira, vida, 
            luz, línea, lista, máquina, hombre, mapa, material, carne, medio, milla, 
            leche, mente, minuto, dinero, mes, luna, boca, música, nación, noche,
            nariz, nota, número, objeto, océano, oficina, párrafo, parque, parte,
            fiesta, pasado, persona, libra, presidente, problema, producto,
            propiedad, pregunta, carrera, radio, lluvia, razón, registro, región, 
            anillo, río, carretera, roca, fila, regla, arena, escuela, ciencia,
            mar, asiento, segunda, oración, conjunto, lado, señal, hermana, tamaño,
            piel, nieve, soldado, solución, acción, edad, aire, animal, respuesta,
            manzana, arte, bebé, espalda, pelota, página, par, papel, hijo, primavera, 
            cuadrado, estrella, estado, detener, calle, estudiante, azúcar, sol,
            pueblo, vocal, guerra, clima, peso, esposa, ventana, invierno, mujer,
            palabra, mundo, año, mi, tu, su, nuestro, vuestro, este, ese, estos, 
            esos, alto, elevado, bajo, largo, grande, en, forma, pequeño, triste,
            enojado, feliz, nervioso, molesto, loco, hambriento, comprensivo,
            redondo, triangular, afilado, rectangular, ancho, sensible, amistoso, 
            educado, perezoso, inteligente, agradable, sucio, mojado, seco,
            apestoso, genial, saludable, caliente, frío, ruidoso, dulce, salado, 
            amargo, agrio, delicioso, repugnante, picante, suave, insípido, helado,
            fresco, español, inglés, francés, italiano, horrible, hirviente, fascinante,
            furioso, enorme, impecable, maravilloso, azul, oscuro, cero, uno, dos,
            tres, cuatro, cinco, seis, siete, ocho, nueve, diez, once,
    tarde -> resultado += lexer.lexeme + ": Es una palabra correcta " + tokens + " \n";
    
    
    
    
                default ->         resultado += " Token: " + tokens + "\n";
                }
                
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        

  
       
      
        
    }//GEN-LAST:event_btnTraducirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jtextPalabra.setText(null); 
        lblelex.setText(null);
        lblesintax.setText(null);
        lblTraduccion.setText(null);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTraducir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jtextPalabra;
    private javax.swing.JTextArea jtextPalabra1;
    // End of variables declaration//GEN-END:variables
}
