/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package translate;

/**
 *
 * @author USUARIO
 */
public enum Tokens {
    
    //sustentivos
    cama, 
   
    factura,
    pájaro, 
    sangre,
    bote,
    cuerpo,
    hueso,
    libro,
    fondo, 
    caja,
    niño,   hermano,   
    edificio, negocio, llamada, capital, caso, gato, causa, centavo, centro, 
    siglo, oportunidad, cambio, verificación,  iglesia, círculo, ciudad, 
    clase, ropa, nube, costa, color, compañía, consonante, copia, maíz, algodón,
    país, curso, vaca, multitud, día, diccionario, dirección, distancia,
    doctor, dólar, puerta, oreja, tierra, huevo, energía, ejemplo, 
    experiencia, ojo, juego, jardín, gas, niña, vidrio, oro, gobierno, 
    césped, grupo, cabello, mano, sombrero, cabeza, corazón, calor, historia,
    agujero, hogar, caballo, hora, casa, hielo, idea, pulgada, banco, industria,
    información, insecto, interés, hierro, isla, trabajo, clave, lago, 
    lenguaje, ley, pierna, nivel, mentira, vida, luz, línea, lista, máquina,
    hombre, mapa, material, carne, medio, milla, leche, mente, minuto, dinero,
    mes, luna, boca, música, nación, noche, nariz, nota, número, objeto,
    océano, oficina, párrafo, parque, parte, fiesta, pasado, persona, libra,
    presidente, problema, producto, propiedad, pregunta, carrera, radio, lluvia,
    razón, registro, región, anillo, río, carretera, roca, fila, regla, arena,
    escuela, ciencia, mar, asiento, segunda, oración, conjunto, lado, señal, 
    hermana, tamaño, piel, nieve, soldado, solución, acción, edad, aire, animal,
    respuesta, manzana, arte, bebé, espalda, pelota, página, par, papel, hijo,
    primavera, cuadrado, estrella, estado, detener, calle, estudiante, azúcar, 
    sol, pueblo, vocal, guerra, clima, peso, esposa, ventana, invierno, mujer,
    palabra, mundo, año,

      //adjetivos
    mi, tu, su, nuestro, vuestro, este, ese, estos, esos, 
    alto, elevado, bajo, largo, grande, en, forma, pequeño,
    triste, enojado, feliz, nervioso, molesto, loco, hambriento,
    comprensivo, redondo, triangular,  afilado, rectangular, 
    ancho, sensible, amistoso, educado, perezoso, inteligente, 
    agradable, sucio, mojado, seco, apestoso, genial, saludable,
    caliente, frío, ruidoso, dulce, salado, amargo, agrio, delicioso, 
    repugnante, picante, suave, insípido, helado, fresco, español, inglés, 
    francés, italiano, horrible, hirviente, fascinante,  
    furioso, enorme, impecable, maravilloso, azul, oscuro, 
    cero, uno, dos, tres, cuatro, cinco, seis, siete, ocho, nueve, diez, once,
    doce, trece, catorce, quince, dieciséis, diecisiete, dieciocho, diecinueve, 
    veinte, treinta, cuarenta, cincuenta, sesenta, setenta, ochenta, noventa,
      cien, doscientos,  mil,  millón,  primero, segundo, tercero, cuarto, quinto,
      sexto, séptimo, octavo, noveno, décimo, undécimo, duodécimo, decimotercero, 
      decimocuarto, decimoquinto, decimosexto, decimoséptimo, decimoctavo,
      decimonoveno, vigésimo, trigésimo, cuadragésimo, quincuagésimo, sexagésimo, 
      septuagésimo, octogésimo, nonagésimo,  nonagésimo_segundo,
      nonagésimo_tercero, nonagésimo_cuarto, centésimo, milésimo, millonésimo,
      todo, cualquier, ambos, cada, cualquiera, suficiente, pocos,
      menos, poco, mucho, más, muchos,  otro, otros, varios, algunos, tal,
      el, la, los, las, un, una, Yo, él, ella, ello, nosotros, ustedes, ellos,
       a,  de, quién, qué, cuál, es, son, soy,abandonar, abolir, absolver, 
       absorber, abusar, acceder, acelerar, acentuar, aceptar, acusar, 
       acostumbrar, lograr, adquirir, actuar, añadir, dirigirse ,
       admirar, admitir, adorar, adornar, avanzar, anunciar, 
       aconsejar, afirmar, estar, acuerdo, permitir, ascender, 
       divertir,  molestar, responder, disculparse, aparecer,
       nombrar, acercarse, aprobar, organizar, llegar, preguntar,
       asegurar, sorprender, atacar, intentar, asistir, atraer,
       evitar, bañar, rogar, creer, pertenecer, culpar, reservar, 
       llamar, llevar, cobrar, cesar, cambiar, verificar, 
       limpiar, despejar, trepar, cerrar, recoger, peinar, combinar, 
       ordenar, comprometer, comparar, quejarse, componer, ocultar, 
       considerar, consistir, contener, continuar, copiar, corregir,
       toser, contar, cubrir, cruzar, coronar, llorar, dañar, bailar,
       amanecer, engañar, decidir, declarar, defender, entregar, desear, 
       despreciar, destruir, separar, desarrollar, dedicar, devorar, descubrir,
       gustar,  dividir, arrastrar, dejar, caer, secar, ganar, 
       elegir, emplear, incluir, alentar, terminar, disfrutar, entrar,
       establecer, estimar, evocar, intercambiar, esperar, explicar, explotar, 
       exponer, expresar, extraer, fallar, temer, buscar, llenar, 
       pescar, quedar, arreglar, flotar, doblar, seguir, fundar,  jugar,
       reunir, gobernar, otorgar, saludar, proteger, adivinar, manejar, 
       colgar, ocurrir, odiar, calentar, ayudar, contratar,  cazar, 
       apresurarse, imaginar, insinuar, importar, impressionar, mejorar, 
       aumentar,  inventar, invitar, planchar,
       unirse, bromear, saltar, justificar, golpear, matar, besar, tocar, 
      mirar, amar, bajar, mantener, casarse, medir, 
       reparar, mencionar, mover, anotar, notar, numerar, observar,
       obedecer, obligar, ocupar, ofrecer, abrir,  empacar, 
       pintar, pasar, colocar, complacer, poseer, practicar,
       preferir, preparar, presentar, producir, prometer, proponer, jalar,
       castigar, empujar, llover, alcanzar, recibir, referir, rechazar, 
       aliviar, permanecer, recordar, quitar, alquilar,  
       repetir, informar, solicitar, requerir, descansar, regresar, 
       navegar, salvar, parecer, afilar, gritar, firmar, sonreír,
       fumar, sonar, empezar, parar, estudiar, sufrir, sugerir, suponer,  
       hablar, domesticar, saborear, cansar,  probar, agradecer, atar, 
       traducir, viajar, confiar, convertir, unir, usar,
       variar, visitar,  caminar,  lavar, pesar,  trabajar, preocupar, herir,
       
       ser, convertirse ,  morder, soplar, romper,
       traer, construir, comprar, poder, atrapar, venir, costar, 
       cortar, hacer, dibujar, beber, conducir, comer,  sentir, 
       pelear, encontrar, volar, olvidar, perdonar, congelar, obtener, dar, ir,
       crecer, tener, esconder,  sostener, lastimar,
       saber, guiar,  prestar, perder,  significar, conocer, 
       pagar, poner, leer, montar,  levantarse, correr, decir, ver, vender,
       enviar, nadar, tomar, enseñar,  pensar, lanzar, entender, despertar, 
       escribir, fui, convertí, empecé, mordí, soplé, rompí, traje,
       construí, compré, pude, atrapé, elegí, vine, costó, corté, hice, dibujé,
       bebí, conduje, comí, caí, sentí, peleé, encontré, volé, olvidé, perdoné,
       congelé, obtuve, di, crecí, colgué, tuve, escondí, golpeé, sostuve, 
       lastimé, mantuve, supe, guié, dejé, presté, permití, perdí, significué,
       conocí, pagué, puse, leí, monté, llamé, soné,  levanté, corrí, dije, vi,
       vendí, envié, mostré, cerré, canté,  hundí,  senté, dormí,
       hablé, gasté, robé, nadé, tomé, enseñé, pensé, lancé, entendí, 
       desperté, usé, gané, escribí, fuiste,
       ahora, ayer, hoy, mañana, antes, anoche, todavía, cuando, después, 
       entonces, mientras, nunca, siempre, tarde, aún, ya,
       aquí, allí, allá,  afuera, abajo,  alrededor, arriba,
       atrás, cerca, debajo, donde, enfrente,  fuera, lejos,  algo, nada, apenas, 
        casi, cuánto, demasiado, 
        solo, mitad, tan, tanto, así, bien, mal, cómo,
        lentamente, rápido, lento, si, supuesto, exacto, 
        realmente, ciertamente, seguramente, justo, no,  quizás, probablemente,
        Inexistentes, Numero, Reservadas, futbol, blanco,    quedarse,
   semana, lunes, martes, miercoles, jueves, viernes,
    sabado, domingo, enero, febrero, marzo, abril, mayo, junio, julio,
    agosto, septiembre, octubre, noviembre, diciembre,  cancelar, 
     escoger,    encajar, 
    conseguir, oir, aprender,
   querer, necesitar, 
    girar, comenzar, mostar, escuchar,  vivir,
    proveer, sentarse, 
    reunirse, ajustar, liderar, comprender,  crear, 
 gastar, r, resperar, enfadado,sediento, cansado, 
    soñoliento, aburrido,
    emocionado,  avergonzado, agradecido, entretenido, indignado, irritado,
    ansioso, inquieto, cauteloso, terco, comodo, seguro, confundido, desanimado, valiente, confiado,
    celoso, calmado, orgulloso, atento, arrogante, ambicioso, artistico, gruñon, mandon,
    carismatico, sociable, fiable, sincero, rudo,amigable, generoso,
    torpe, despistado, alegre, travieso, mimado, animado, precioso, creativo,
    imaginativo, trabajador, atractivo, listo, tranquilo, humilde, tacaño,
    rico, encantador, guapo, estupido, quisquilloso, despiadado, feo, joven, liso, 
    duro, aspero,pesado, ligero, radiante,  hueco, solido, minusculo,
   corto, desafilado, grueso, fino,temprano,  consider, ERROR,
 
  
}
